### ISSUE TITLE
&> log

### ISSUE THREAD

**Issue by mohsenuss91** [Jokeren/DataMining-gSpan#1]
@Jokeren What do you mean by &> log ?

**Comment by Jokeren** [comment]
I explain it in the latest `readme` file. 

Because I have not included a separated log-writer in the program, so I use standard output stream-`printf` to write the result on the console. To redirect the result to the files, you should use redirect operators. 

Thanks for your comment, I was preparing for my exam in the last few weeks so that don't have time to update the project.

This program is done under the instruction of my mentor, he want me to practice parallel&concurrent programming skills in data-mining, therefore I will try to add MPI, Cuda or other features in the future. Also, some fine-grained parallel algorithm will be applied.
